### ISSUE TITLE
sync.sh fails since npm format is missing in ory/docs

### ISSUE THREAD

**Issue by vinckr** [ory/meta#146]
This is the line in sync that is failing:
https://github.com/ory/meta/blob/cfbed4ba43e5560e71d3b780ff2c90b8f3bb04e6/scripts/sync.sh#L58

failed CI run:
https://github.com/ory/meta/actions/runs/2460840415

Commit that removes npm format in /docs:
https://github.com/ory/docs/commit/701a4932183c3f1fb144e49e3cb893c515d235f1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Should we add another check for ory/docs or can we add a npm format dummy command @aeneasr ?

**Comment by aeneasr** [comment]
@zepatrik removed formatting from the docs, I'll add a dummy check.

**Comment by aeneasr** [comment]
https://github.com/ory/docs/pull/857
