### ISSUE TITLE
syncing that also removes files

### ISSUE THREAD

**Issue by kevgo** [ory/meta#150]
extracted from https://github.com/ory/prettier-styles/pull/55#issuecomment-1160105459:

>> How do we delete the now obsolete [.github/semantic.yml](https://github.com/ory/prettier-styles/blob/master/.github/semantic.yml) from all repos? After a cursory glance, I see the sync script only copying files from the meta repo to the target repos (except for the ISSUE_TEMPLATE directory, which it clears out first).
>
> Good question, it might make sense to use rclone / rcopy instead of a dumb `cp`?

**Comment by kevgo** [comment]
Super low-tech solution: give the filenames of all synced files a suffix that identifies them as synced. For example, if I'm about to create a file `.github/workflows/foo.yml` in the `meta` repo that we want to sync to each Ory repo, we would name it `.github/workflows/foo_synced.yml` instead. Then, when we sync, we delete all synced files (`find . -name '*_synced.*' -exec rm {} \;`) in the target repo and then `cp -r` all the new files from `meta` over to it.

A challenge is migrating to this new state.

**Comment by kevgo** [comment]
This is so rare (happens the first time now, in the future maybe once a year) that it might make sense to keep it as manual toil for now. Deleting a file manually from all repos can be done in an hour using the GitHub UI.

Find all files called `semantic.yml` in the github.com/ory organization: https://github.com/search?q=org%3Aory+filename%3Asemantic.yml&type=Code

Find all mentions of that file in the github.com/ory org: https://github.com/search?q=org%3Aory+semantic.yml&type=Code

Open each search result in a new tab and delete/edit using the GitHub UI. Try to use [auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) to get these robo-PRs merged semi-automatically.

If we find ourselves batch-deleting files a lot from all repos, we'll have a reason to invest in automating this.

**Comment by jonas-jonas** [comment]
didn't come up again.
