### ISSUE TITLE
Conventional commits fails with false negative

### ISSUE THREAD

**Issue by aeneasr** [ory/meta#158]
This PR has the correct title https://github.com/ory/kratos/pull/2593 but the CI failed for conventional commits. Can you PTAL @kevgo ? TY!

**Comment by vinckr** [comment]
i think its because `sdk` is not part of the scopes

```
          scopes: |
            blog
            cms
            deps
            docs
            home
            hydra
            keto
            kratos
            stats
```

**Comment by kevgo** [comment]
Yes, a few scopes are missing: sdk, console, backoffice. This is the type of feedback we need to fine-tune this action. @zepatrik has already sent a PR to upstream: https://github.com/amannn/action-semantic-pull-request/pull/193

**Comment by kevgo** [comment]
This is fixed now and can be closed.
