### ISSUE TITLE
Decide RESTful PATCH strategy

### ISSUE THREAD

**Issue by aeneasr** [ory/meta#2]
We do not support PATCH methods for our HTTP REST endpoints. We should pick an appropriate standard to support PATCH.

The most obvious approach would be [JSON Patch](http://jsonpatch.com), formalized as [IETF RFC 6902](http://jsonpatch.com). I haven't done research for additional methods yet.

**Comment by DennisPattmann5012** [comment]
Maybe **JSON Merge Patch** could be an alternative.

[IETF RFC 7396](https://tools.ietf.org/html/rfc7396)

**Comment by aeneasr** [comment]
It was decided! https://github.com/ory/hydra/pull/2411
