### ISSUE TITLE
Add synchronization for `ory/elements`

### ISSUE THREAD

**Issue by jonas-jonas** [ory/meta#202]
https://github.com/ory/elements still uses the old PR template (with typos ;)) and the README is different. We should add `ory/elements` to the synchronized repositories, but I suspect there is some additional work necessary to adjust the README in that Repo.

**Comment by kevgo** [comment]
Great idea! To add ory/elements to the sync, just add it somewher into https://github.com/ory/meta/blob/master/scripts/sync.sh#L21-L83. I assume as a `library` but please double-check with Aeneas.

Please note that the sync will overwrite the files in your repo with the ones in https://github.com/ory/meta/tree/master/templates/repository, particularly the ones in `common` and `library`.

**Comment by jonas-jonas** [comment]
Thanks for the write up, I'll take a look soon.

**Comment by jonas-jonas** [comment]
This has long been done.
