### ISSUE TITLE
Docs: CONTRIBUTING should mention that the CLA needs to be signed

### ISSUE THREAD

**Issue by nessita** [ory/meta#32]
If my reading of the CONTRIBUTING page is correct, there is no mention of the need to sign the CLA. Ideally this would either be listed there or be part of the checklist when submitting a PR.

**Comment by aeneasr** [comment]
@vinckr can you please take this?

**Comment by vinckr** [comment]
@nessita 
You think those changes are sufficient?

**Comment by nessita** [comment]
@vinckr yes, thank you very much!

**Comment by vinckr** [comment]
Great :)
can you or anyone else close the issue? I can't do it. 
Thanks again for pointing it out @nessita
