### ISSUE TITLE
Docs: CONTRIBUTING seems to have a missing template variable replaced

### ISSUE THREAD

**Issue by nessita** [ory/meta#33]
When browsing the CONTRIBUTING for Ory Hydra at https://github.com/ory/hydra/blob/master/CONTRIBUTING.md, the text looks like this:

`Contributing to ORY {{Project}}`

or

`Please note: We take ORY {{Project}}'s security and our users' trust very seriously. If you believe you have found a security issue in ORY {{Project}}, please responsibly disclose by contacting us at office@ory.sh.`

**Reproducing the bug**

Browse https://github.com/ory/hydra/blob/master/CONTRIBUTING.md.

**Expected behavior**

I'm not fully sure what's expected here, the `Project` variable may be being replaced somewhere else or as part of an automated doc generation process, but IMHO it would be handy to have the proper replacement within GH so when a developer goes and read it following the PR checklist, it does not look like it's "not fully rendered".

**Comment by vinckr** [comment]
Could the problem be that the CONTRIBUTING.md is in ` templates/repository/common/` and not in https://github.com/ory/meta/blob/master/templates/repository/CONTRIBUTING.md like specified in the file?

**Comment by aeneasr** [comment]
Possible!

**Comment by vinckr** [comment]
Ok so it seems to be in order in the sync.sh script
https://github.com/ory/meta/blob/a72198265b7fe024ed0eafdda830705eb3ff65ad/scripts/sync.sh#L36
https://github.com/ory/meta/blob/a72198265b7fe024ed0eafdda830705eb3ff65ad/scripts/sync.sh#L38

Is there some other step that I am missing?

**Comment by vinckr** [comment]
This was the commit that broke it
https://github.com/ory/kratos/commit/bdb6875e55aed454cda061969e1dd4f712e09bb5

**Comment by mitar** [comment]
Same happens on Fosite as well: https://github.com/ory/fosite/issues/521

**Comment by vinckr** [comment]
Hmm thanks for that mitar! I think its actually a good clue that it is only broken for some repos not all, oathkeeper for example its still working. 
I will try and do a deep investigation later today.

**Comment by aeneasr** [comment]
@vinckr yeah I think https://github.com/ory/meta/issues/33#issuecomment-717912973 would be the correct bug. You can check "git blame". Do you have a linux system?

**Comment by vinckr** [comment]
I have ubuntu subsystem yes. 

After looking at blame I think its
[fix: pick sed command based on os](https://github.com/ory/meta/commit/7b0792e11275088abbf5207b8f56a5e881b125c1)
that broke it, before it was working fine. 

How could I test if it is working or not locally?

**Comment by aeneasr** [comment]
I see, I think the order is reverted - so the darwin stuff is the linux stuff and vice versa

**Comment by aeneasr** [comment]
Can you fix this @vinckr ?
