### ISSUE TITLE
sync.sh meta discussion replacement

### ISSUE THREAD

**Issue by vinckr** [ory/meta#85]
sync.sh does not replace `discussions="https://github.com/$project/discussions"` as intended for projects using /meta/discussion.

It ignores the `https://github.com/ory/meta/discussions` replacement and creates links like 
[ORY Fosite Discussions](https://github.com/ory/fosite/discussions). 

For example the sync.sh run for `ory/kratos-selfservice-ui-react-native` :
https://github.com/ory/meta/runs/1707608653?check_suite_focus=true
```
+ [[ ory/kratos-selfservice-ui-react-native = \o\r\y\/\h\y\d\r\a ]]
+ [[ ory/kratos-selfservice-ui-react-native = \o\r\y\/\k\r\a\t\o\s ]]
+ [[ ory/kratos-selfservice-ui-react-native = \o\r\y\/\o\a\t\h\k\e\e\p\e\r ]]
+ [[ ory/kratos-selfservice-ui-react-native = \o\r\y\/\k\e\t\o ]]
+ env -i DISCUSSIONS=https://github.com/ory/meta/discussions REPOSITORY=ory/kratos-selfservice-ui-react-native 'PROJECT=Kratos SelfService UI React Native Example' /bin/bash -c 'envsubst < "/tmp/tmp.ejdMiUZBpw/CONTRIBUTING.md" | sponge "/tmp/tmp.ejdMiUZBpw/CONTRIBUTING.md"'
```

I interpret the last line that it would replace $DISCUSSIONS with `https://github.com/ory/meta/discussions`.
But instead it uses `https://github.com/ory/kratos-selfservice-ui-react-native/discussions`.

Not sure where it comes from, is there a replacement step before this that im missing?  

When I test it locally it works correctly
``` 
#test.sh: 

#!/bin/bash

set -Eexuo pipefail

    humanName="kratos-selfservice-ui-react-native"
    project=ory/kratos-selfservice-ui-react-native
    discussions="https://github.com/$project/discussions"
    

    for f in $(find "CONTRIBUTING.md" -type f -print); do
        if [[ "$project" = "ory/hydra" || $project = "ory/kratos" || $project = "ory/oathkeeper" || $project = "ory/keto" ]]; then
          env -i DISCUSSIONS="$discussions" REPOSITORY="$project" PROJECT="$humanName" /bin/bash -c "envsubst < \"$f\" | sponge \"$f\""
        else
          env -i DISCUSSIONS="https://github.com/meta/discussions" REPOSITORY="$project" PROJECT="$humanName" /bin/bash -c "envsubst < \"$f\" | sponge \"$f\""
        fi
    done

```

Maybe it should replace with an env variable as well instead of the URL? 
like: 
`metaDiscussions="https://github.com/meta/discussions"`
`DISCUSSIONS="$metaDiscussions"`

I will look if I can find a solution, but kinda of stuck at the moment...

**Comment by aeneasr** [comment]
`DISCUSSIONS="$metaDiscussions"` should work! Also `metaDiscussions="https://github.com/meta/discussions"`!
